version: 2
jobs:
  build:
    working-directory: ~/farbton
    docker:
      - image: circleci/node:10.6.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install all dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run-script lint
      - run:
          name: compile
          command: npm run-script compile
